### ISSUE TITLE
Porting Jupyter Notebook  setup

### ISSUE THREAD

**Issue by adishourya** [Bekaboo/nvim#5]
I absolutely love your jupyter setup with jupytext and molten-nvim.
But I am finding it difficult to replicate it on a vanilla nvim setup .
Any tips on how to port it cleanly.

Thankyou so much for M Λ C R O.

**Comment by Bekaboo** [comment]
Thanks for your words!

> But I am finding it difficult to replicate it on a vanilla nvim setup .

Are you using a plugin manager, e.g. lazy.nvim? If so, all third-party markdown/notebook-related plugin specs are in [lua/modules/markup.lua](https://github.com/Bekaboo/nvim/blob/master/lua/modules/markup.lua), you can refer to [lazy.nvim's README](https://github.com/folke/lazy.nvim#-plugin-spec) if you are unfamiliar with the format of the spec.

Config for each plugin goes into [lua/configs/](https://github.com/Bekaboo/nvim/tree/master/lua/configs), e.g. the config file for molten is [lua/configs/molten.lua](https://github.com/Bekaboo/nvim/blob/master/lua/configs/molten.lua) and it is required by the plugin spec of molten which is inside [lua/modules/markup.lua](https://github.com/Bekaboo/nvim/blob/master/lua/modules/markup.lua)

On the other hand, I use a custom plugin (sometimes I call them built-in plugins) to convert jupyter notebooks into markdown files so that I can edit it using nvim. The plugin is located at [lua/plugin/jupytext.lua](https://github.com/Bekaboo/nvim/blob/master/lua/plugin/jupytext.lua). To use it you simply put it under the same path and call `require('plugin.jupytext').setup()` somewhere in your config.

Let me know if you have any other questions.
